language: node_js
node_js:
- 10.5
deploy:
  provider: cloudfoundry
  api: https://api.fr.cloud.gov
  username: dweaver@topcoder.com
  password:
    secure: SoPSkW/LebCdqeOeP2ohawsz1jgPv4mpendG0bwI2a/h1v6lY3lH4qn4ljtr6aWOx9aOxSX+TEBs4eFmRk37ADT0r3LFQUqgPxElvLZyYGjktN37UOiWD7fyPw3SGXUBEVyydkvcX6VSCkOknLwYDv13269GrfuH7AQ08s26IdRGwFV26HeJ5foByJmD+5uaJuberbyb40ps8HUncgovXwX9jh5NftGp/7WZq1wIxAAOP5dhuCpCbiFbb/nt3zic2XvNsiabGDPJ3Rue+e+Ca20uPo2tgo8mp5uGFG9iPPB1RWyYkqdtyvFyxy0g7EGLBnkWYNANnI+05XMcWY9zIGa+S1YjWKArgk3MGZa8QWYOha7VyWCWLYuDH4R0UMmyQinLx/o5zKo4B+FdTAgSVae3r6ERXg2+BZ2V61Nc7OA362HT5AiUd+yo1k+BdIjaZeSXdULIppzCkvo+BEteeWp+9f/Pn6sUAgFFB05FxHMbL0kfrCYWpCAMBpNMzDbmo4qHlTzV6gDS3LCazodYIzklQJXfbX+GKMr1GwRA6R9d2AP4bzw4DdBUWn0CUWEZ9fO9JWYdEkSCK1uKvH+OcYMkFAk3I2BPZ/IgkjLFmqMYa+HiMQTT+CDjPih8ozZ08ORHvMCJrbyd8skg0J0VcN6SsDXelV7rR7jmOjuu7FI=
  organization: sandbox-va
  space: rest-api
  on:
    repo: topcoderinc/va-online-memorial-rest-api
    branch: prototype
