language: node_js
node_js:
- 10.5
deploy:
  provider: cloudfoundry
  api: https://api.fr.cloud.gov
  username: dweaver@topcoder.com
  password:
    secure: L9Ic8ecvp9tI84DuV5vJTfnO+qsEQn90yflH/+ix0hVS33p5TT7N78JS9CQS9OnVC/z9+RER3xDTD3OC2MS7L0laFUJYxl2H6cP5qH2IC+haCxMJTnr6EPCV989hVHm4qXqX9ALphwTogqGsyIn9tgrmXdqbJ+M3lytjIYSGtFfluMsTiGIiXOGAXea8hRmXbktyZBEPUrzfZ0V9XQPZXxk60EMX30iG3AwwG5MGCfLHBXwUWWTt2LSP8U9HIlu2lAI8e/ODci+woNSH5rGGgzRVggotyIP8FsfedFd0+5rMkWhrqoj5ynGT15BonkdrjfCQahrZsMNlDOxz24cH9t2p0T54VV0zgEG/qkMNJl+wyj/nPs8t7PJEJK8pC38WxmvDG+pZvYdsxOLBIMM/195i+yCPF6dxcomcCRQg6HA7YB+rOQMshqwoPOxYSOSc349FWiquQy6KM+wjWVWdQjUIW+kDgAZMTapA1oLQ2h5BKVqhA5Jq9UjUNR8d0pYbEIYAMk5p5u7znEKcw5OXym448HJUgybY1qEPEMpR44Cx76C7vv7RKrP96aGb2mM0pH/A2r2366yCs3HSLZd4lvFQD9oPhyyp9csdsxBMaqN/wY34LPwXDR70gjK9d9st9Wk08M5WDwvpPnmCC8m95N7QDeT1NGvWPGui/DTSBDU=
  organization: sandbox-va
  space: frontend
  on:
    repo: topcoderinc/va-online-memorial-rest-api
    branch: prototype
